// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timely.Data;

#nullable disable

namespace Timely.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251016200019_updateinvoices")]
    partial class updateinvoices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Timely.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Timely.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NationalityId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Timely.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Handles all technical and IT-related tasks",
                            Name = "IT Department",
                            Uid = "d7b4e4a6-4c9a-4f21-9a33-1f2b7d8e9a01"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Responsible for employee relations and recruitment",
                            Name = "HR Department",
                            Uid = "b3c1d8f7-5a8e-4f2a-8c33-9f1a2b7d5e02"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manages budgets, payroll, and accounting",
                            Name = "Finance Department",
                            Uid = "e9f6a1c2-2b8a-42b1-bd3f-5c9a3f2d8a03"
                        });
                });

            modelBuilder.Entity("Timely.Models.DepartmentWorking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ServiceId");

                    b.ToTable("DepartmentWorkings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Day = "Sunday",
                            DepartmentId = 1,
                            EndTime = new DateTime(2024, 10, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Morning Shift",
                            StartTime = new DateTime(2024, 10, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Uid = "a1b2c3d4-e5f6-7890-ab12-cd34ef56a101"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Day = "Sunday",
                            DepartmentId = 1,
                            EndTime = new DateTime(2024, 10, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Evening Shift",
                            StartTime = new DateTime(2024, 10, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Uid = "b2c3d4e5-f6a7-8901-bc23-de45f678b202"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Day = "Monday",
                            DepartmentId = 2,
                            EndTime = new DateTime(2024, 10, 1, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Morning Shift",
                            StartTime = new DateTime(2024, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Uid = "c3d4e5f6-a7b8-9012-cd34-ef56a789c303"
                        });
                });

            modelBuilder.Entity("Timely.Models.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("Timely.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentWorkingId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NationalityId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DepartmentWorkingId");

                    b.HasIndex("JobId");

                    b.HasIndex("NationalityId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 10, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            DepartmentWorkingId = 1,
                            Email = "ahmed.ali@example.com",
                            JobId = 1,
                            Name = "Ahmed Ali",
                            NationalityId = 1,
                            Password = "123",
                            Phone = "+966512345678",
                            Uid = "c8a25f76-1b4a-4d9b-9b84-1a6c4e8b8f11"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 10, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            DepartmentWorkingId = 1,
                            Email = "sara.mohammed@example.com",
                            JobId = 2,
                            Name = "Sara Mohammed",
                            NationalityId = 2,
                            Password = "123",
                            Phone = "+966523456789",
                            Uid = "a5f3b9d2-4f6c-4d89-a317-9c9a8c6d9b22"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 10, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            DepartmentWorkingId = 2,
                            Email = "khalid.faisal@example.com",
                            JobId = 3,
                            Name = "Khalid Al-Faisal",
                            NationalityId = 3,
                            Password = "123",
                            Phone = "+966534567890",
                            Uid = "f7b4d2a9-87cd-42a1-93c2-12e4a9e6d4c3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 10, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            DepartmentWorkingId = 2,
                            Email = "laila.hassan@example.com",
                            JobId = 4,
                            Name = "Laila Hassan",
                            NationalityId = 4,
                            Password = "123",
                            Phone = "+966545678901",
                            Uid = "e9d5c2a7-4b2e-46f8-a1c9-5f9a3e2d1b44"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 10, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            DepartmentWorkingId = 3,
                            Email = "omar.nasser@example.com",
                            JobId = 5,
                            Name = "Omar Nasser",
                            NationalityId = 5,
                            Password = "123",
                            Phone = "+966556789012",
                            Uid = "b3f9a8c6-9d4e-42f3-bc9a-1e7a2c6f8b55"
                        });
                });

            modelBuilder.Entity("Timely.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("PaymentId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Timely.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BaseSalary")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSalary = 8500.0,
                            CreatedAt = new DateTime(2024, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Software Engineer",
                            Uid = "d4e5f6a7-b8c9-0123-de45-f678a9bcd401"
                        },
                        new
                        {
                            Id = 2,
                            BaseSalary = 7000.0,
                            CreatedAt = new DateTime(2024, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HR Specialist",
                            Uid = "e5f6a7b8-c9d0-1234-ef56-a789bcd0e502"
                        },
                        new
                        {
                            Id = 3,
                            BaseSalary = 12000.0,
                            CreatedAt = new DateTime(2024, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Project Manager",
                            Uid = "f6a7b8c9-d0e1-2345-f678-b9cd0e1f6303"
                        },
                        new
                        {
                            Id = 4,
                            BaseSalary = 6500.0,
                            CreatedAt = new DateTime(2024, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Accountant",
                            Uid = "a7b8c9d0-e1f2-3456-a789-cd0e1f2a7404"
                        },
                        new
                        {
                            Id = 5,
                            BaseSalary = 6000.0,
                            CreatedAt = new DateTime(2024, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Graphic Designer",
                            Uid = "b8c9d0e1-f2a3-4567-b89a-d0e1f2a3b505"
                        });
                });

            modelBuilder.Entity("Timely.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Syrian"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Saudi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Egyptian"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jordanian"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lebanese"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Iraqi"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Yemeni"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Kuwaiti"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Emirati"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Qatari"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Omani"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bahraini"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Sudanese"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Moroccan"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Algerian"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Tunisian"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Libyan"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Palestinian"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Turkish"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Iranian"
                        },
                        new
                        {
                            Id = 21,
                            Name = "American"
                        },
                        new
                        {
                            Id = 22,
                            Name = "British"
                        },
                        new
                        {
                            Id = 23,
                            Name = "French"
                        });
                });

            modelBuilder.Entity("Timely.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ClientId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Timely.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Timely.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Admin",
                            Permission = "FullAccess",
                            Uid = "e12a4b15-4b8d-4b2a-bc9b-0f1a3b2f3a11"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Manager",
                            Permission = "ManageUsers,ViewReports",
                            Uid = "a47b9e72-3a92-44d2-8a0c-5a1d4b8e7a22"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "User",
                            Permission = "ViewOwnData",
                            Uid = "b92d5e64-1f23-4c91-96f8-6b2e4d9c8c33"
                        });
                });

            modelBuilder.Entity("Timely.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("TypeServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("TypeServiceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Timely.Models.TypeService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeServices");
                });

            modelBuilder.Entity("Timely.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmed.ali@example.com",
                            Name = "Ahmed Ali",
                            Password = "123456",
                            Phone = "0551234567",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "sara.mohammed@example.com",
                            Name = "Sara Mohammed",
                            Password = "123456",
                            Phone = "0569876543",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "omar.nasser@example.com",
                            Name = "Omar Nasser",
                            Password = "123456",
                            Phone = "0571122334",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "laila.hassan@example.com",
                            Name = "Laila Hassan",
                            Password = "123456",
                            Phone = "0583344556",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 5,
                            Email = "khalid.faisal@example.com",
                            Name = "Khalid Al-Faisal",
                            Password = "123456",
                            Phone = "0596677889",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Timely.Models.Appointment", b =>
                {
                    b.HasOne("Timely.Models.Client", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId");

                    b.HasOne("Timely.Models.Employee", "Employee")
                        .WithMany("Appointments")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Timely.Models.Client", b =>
                {
                    b.HasOne("Timely.Models.Nationality", "Nationality")
                        .WithMany("Clients")
                        .HasForeignKey("NationalityId");

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("Timely.Models.DepartmentWorking", b =>
                {
                    b.HasOne("Timely.Models.Department", "Department")
                        .WithMany("DepartmentWorkings")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Timely.Models.Service", "Service")
                        .WithMany("DepartmentWorkings")
                        .HasForeignKey("ServiceId");

                    b.Navigation("Department");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Timely.Models.Detail", b =>
                {
                    b.HasOne("Timely.Models.Appointment", "Appointment")
                        .WithMany("Details")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Timely.Models.Employee", b =>
                {
                    b.HasOne("Timely.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timely.Models.DepartmentWorking", "DepartmentWorking")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentWorkingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timely.Models.Job", "Job")
                        .WithMany("Employees")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timely.Models.Nationality", "Nationality")
                        .WithMany("Employees")
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("DepartmentWorking");

                    b.Navigation("Job");

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("Timely.Models.Invoice", b =>
                {
                    b.HasOne("Timely.Models.Appointment", "Appointment")
                        .WithMany("Invoices")
                        .HasForeignKey("AppointmentId");

                    b.HasOne("Timely.Models.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId");

                    b.HasOne("Timely.Models.Payment", "Payment")
                        .WithMany("Invoices")
                        .HasForeignKey("PaymentId");

                    b.Navigation("Appointment");

                    b.Navigation("Client");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Timely.Models.Payment", b =>
                {
                    b.HasOne("Timely.Models.Appointment", "Appointment")
                        .WithMany("Payments")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timely.Models.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Timely.Models.Review", b =>
                {
                    b.HasOne("Timely.Models.Client", "Client")
                        .WithMany("Reviews")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timely.Models.Service", "service")
                        .WithMany("Reviews")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("service");
                });

            modelBuilder.Entity("Timely.Models.Service", b =>
                {
                    b.HasOne("Timely.Models.Department", "Department")
                        .WithMany("Services")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timely.Models.TypeService", "TypeService")
                        .WithMany("Services")
                        .HasForeignKey("TypeServiceId");

                    b.Navigation("Department");

                    b.Navigation("TypeService");
                });

            modelBuilder.Entity("Timely.Models.User", b =>
                {
                    b.HasOne("Timely.Models.Role", "Roles")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Timely.Models.Appointment", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Invoices");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Timely.Models.Client", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Invoices");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Timely.Models.Department", b =>
                {
                    b.Navigation("DepartmentWorkings");

                    b.Navigation("Employees");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Timely.Models.DepartmentWorking", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Timely.Models.Employee", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Timely.Models.Job", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Timely.Models.Nationality", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Timely.Models.Payment", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Timely.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Timely.Models.Service", b =>
                {
                    b.Navigation("DepartmentWorkings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Timely.Models.TypeService", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
